server:
  port: 8080

spring:
  application:
    name: "custom-auth-server"
  datasource:
    url: "${DB_URL}"
    username: "${DB_USER}"
    password: "${DB_PASSWORD}"

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  flyway:
    enabled: true

  logging:
    level:
      root: INFO
      org.hibernate.SQL: INFO
      org.flyway: DEBUG
    config: classpath:logback-spring.xml

app:
  jwt:
    issuer: "${ISSUER:https://auth.local}"
    audience: "${JWT_AUDIENCE:auth-api}"
    secret-base64: "${JWT_SECRET_BASE64:}"
    access-token-ttl-seconds: "${ACCESS_TOKEN_TTL_SECONDS:900}"
  refresh-token-ttl-days: 14